### ISSUE TITLE
shape tool(s)

### ISSUE THREAD

**Issue by SuperOP535** [OurSources/owop-client#10]
oval/circle, square, rectangle, triangle, star, heart etc

**Comment by SuperOP535** [comment]
oval/circle, square, rectangle, triangle, star, heart etc

**Comment by Sigma-One** [comment]
This would be a good feature for those who actually do art, but could make griefing quite a bit easier.

**Comment by SuperOP535** [comment]
Not really as it would be as slow as the fill tool is

**Comment by DayDun** [comment]
Shape tool won't come before accounts
