### ISSUE TITLE
chat formatting

### ISSUE THREAD

**Issue by SuperOP535** [OurSources/owop-client#16]
as seen on discord, github **bold** _italic_ __underline__ (<-github does not support) ~~strikethrough~~

**Comment by DayDun** [comment]
We need to decide on a format first.
Suggestion:
\*bold\*
\~italic\~
\-strikethrough\-
\_underline\_

Not too sure on the italic one, I wouldn't want bold and italic to use the same character though.

**Comment by Nurutomo** [comment]
*bold*
_italic_
~strikethrough~
__underline__

**Comment by Nurutomo** [comment]
```
*bold*
_italic_
~strikethrough~
__underline__
```
Maybe this is good, deleted comments are failure to type format

**Comment by DayDun** [comment]
I don't like the same character doing two styles, I don't see how _ correlates to italics either
