### ISSUE TITLE
how to start pls answer

### ISSUE THREAD

**Issue by mathias377** [OurSources/owop-client#30]

**Comment by kcinnu** [comment]
are you sure you wanted to open this issue in `owop-client` and not `owop-server`? also, "pls answer" only makes it look like you wont even be able to start the server even with a guide, and wont help you get an answer faster.

**Comment by SuperOP535** [comment]
note: owop-server is not done

**Comment by mathias377** [comment]
oh

**Comment by mathias377** [comment]
how to start owop server or compile
