### ISSUE TITLE
Add support JQuery in OWOP

### ISSUE THREAD

**Issue by LDG1** [OurSources/owop-client#33]
$.getScript is not defined

**Comment by DayDun** [comment]
please no, there is not a single good reason in the universe to add jquery to owop.

**Comment by kcinnu** [comment]
and if you really want to use jquery for some reason, then you can just use dom to append a script element to load jquery to the document body, like this:
```javascript
const script = document.createElement('script');
script.src = 'https://code.jquery.com/jquery-3.3.1.min.js';
document.body.appendChild(script);
```

**Comment by DayDun** [comment]
So you are importing a script that allows you to import another script with a little less code

**Comment by SuperOP535** [comment]
LOL
