### ISSUE TITLE
Cool suggestion here click 

### ISSUE THREAD

**Issue by dimdenGD** [OurSources/owop-client#36]
Pls make r/place world with 1 minute timer and 1000x1000 pixel canvas it would be cool

**Comment by DayDun** [comment]
that's just downgrading, and only motivates botting even more.

**Comment by dimdenGD** [comment]
> that's just downgrading, and only motivates botting even more.

Google Authentification ????

**Comment by SuperOP535** [comment]
🙄🙄🙄🙄🙄🙄🙄🙄

**Comment by mathmakgakpak** [comment]
you want make pixel battle again...

**Comment by mathmakgakpak** [comment]
he did it
...
