### ISSUE TITLE
Cant draw

### ISSUE THREAD

**Issue by F4Tornado** [OurSources/owop-client#7]
One time I was joining to make sure my art wasn't being sabotaged, it was being sabotaged but I couldn't repair it because when I moved the mouse, it would change color to white, and when I used the scroll wheel to select a color, I couldn't click. Reloading wouldn't fix the issue.

Also, when I moved my mouse when the move tool is selected, it would move even though I wasn't clicking.

The only console error was this:
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
app.48285aac6699091d3151.js:642

**Comment by nagalun** [comment]
What browser are you using? (Include full version)

**Comment by F4Tornado** [comment]
Chrome 67.0.3396.62

I'm using the latest version of Chrome

**Comment by nagalun** [comment]
I don't have this version installed atm but I'll take a look.
It seems like it's not detecting the release of the mouse button, and thus it gets stuck picking colors or something. You can confirm this with `OWOP.mouse.buttons` not being 0 after releasing all buttons

**Comment by F4Tornado** [comment]
It seems to randomly fix itself for no clear reason
